### ISSUE TITLE
Verify the event actually came from GitHub

### ISSUE THREAD

**Issue by kylef** [keith/keith-as-a-service#1]
Currently it could be possible to craft a payload and send it to the deployed service which will think it originated from GitHub.

This could have malicious intent and could be designed to provide fake information to make the bot comment and close different issues or pull requests either in the Specs repository, or other repositories.
#### Example payload to close the [pull request FAQ pull request](https://github.com/CocoaPods/Specs/pull/12199):

``` json
{
    "pull_request": {
        "action": "opened",
        "_links": {
            "self": { "href" "https://api.github.com/repos/CocoaPods/Specs/pulls/12199" },
            "comments": { "href": "https://api.github.com/repos/CocoaPods/Specs/issues/12199/comments" }
        }
    }
}
```
#### Example payload to cause the bot to comment on unrelated pull requests on completely different repositories (causing spam)

``` json
{
    "pull_request": {
        "action": "opened",
        "_links": {
            "self": { "href" "https://api.github.com/repos/QueryKit/QueryKit/pulls/32" },
            "comments": { "href": "https://api.github.com/repos/QueryKit/QueryKit/issues/32/comments" }
        }
    }
}
```

Closing the issue would fail, however commenting would still succeed.
### Verifying the signature

The service should look at the `X-Hub-Signature` header and validate it is a correct HMAC signature using the hook's secret (see https://github.com/github/github-services/blob/f3bb3dd780feb6318c42b2db064ed6d481b70a1f/lib/service/http_helper.rb#L77).

**Comment by kylef** [comment]
Oh, and not to mention. Without this change, someone could put in an entirely different link for self and comment to a service outside of GitHub so that the web service will send them the configured GitHub username and password leaking these secrets.

##### Example payload

``` json
{
    "pull_request": {
        "action": "opened",
        "_links": {
            "self": { "href" "http://requestb.in/1g31z8r1" },
            "comments": { "href": "http://requestb.in/1g31z8r1" }
        }
    }
}
```

Once the payload has been sent, visit http://requestb.in/1g31z8r1?inspect and you will see the github username and password in the authorization header.

With these tokens, a person would have write access to the CocoaPods specs repository and could therefore hijack/take over any pod.

**Comment by keith** [comment]
Thanks for spending all the time submitting this, here's the PR https://github.com/keith/keith-as-a-service/pull/2
